Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection 
Traceback: 
[1] "2: readChar(con, 5L, useBytes = TRUE)" "1: load(\"data_respno_FDI.RData\")"   

Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data_respno_FDI.RData', probable reason 'No such file or directory'

